# Generated by Django 5.1.4 on 2025-01-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('password2', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='People',
        ),
    ]
