# Generated by Django 5.0.4 on 2025-01-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0002_peoplereg_rename_users_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
        migrations.AlterField(
            model_name='peoplereg',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='peoplereg',
            name='password2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='peoplereg',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
